<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KrakowOpenData.Api\KrakowOpenData.Api.csproj" />
    <ProjectReference Include="..\..\src\KrakowOpenData.Client\KrakowOpenData.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Fixtures\osm-access-sample.json" Link="Fixtures\osm-access-sample.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
