using KrakowOpenData.Domain.Common;

namespace KrakowOpenData.Domain.Safety;

/// <summary>Which score a citizen report feeds.</summary>
public enum ScoreLayer
{
    Safety,
    Heat,
    Flood,
    Air
}

/// <summary>What a resident can report. Each type feeds exactly one score layer (see <c>ReportRules</c>).</summary>
public enum ReportType
{
    LightOut,
    UnsafeAtNight,
    PathHazard,
    WaterNotWorking,
    NoShade,
    HeatSpot,
    FloodedStreet,
    BlockedDrain,
    RisingWater,
    SmokeOrBurning,
    StrongFumes,
    DustCloud
}

public enum ReportStatus
{
    Open,
    Resolved
}

/// <summary>
/// A resident's report. <see cref="DeviceIds"/> holds the anonymous random ids of everyone who reported or
/// confirmed it: the number of distinct ids is the "independent supporters" count that decides how much the
/// report weighs. The id is a random value generated by the app; it is never linked to a person.
/// </summary>
public sealed record CitizenReport(
    string Id,
    ReportType Type,
    GeoPoint Location,
    string? Note,
    DateTimeOffset CreatedAt,
    DateTimeOffset LastActivityAt,
    IReadOnlyList<string> DeviceIds,
    bool VerifiedByPlanner,
    ReportStatus Status,
    DateTimeOffset? ResolvedAt,
    string? ResolutionNote) : IEntity
{
    public int Supporters => DeviceIds.Count;
}
